function(saccade_resolve_target_architecture output_variable system_processor
         osx_architectures vs_platform generator_platform compiler_architecture)
    set(target_processor "${system_processor}")
    if(osx_architectures)
        set(architecture_list ${osx_architectures})
        list(LENGTH architecture_list architecture_count)
        if(NOT architecture_count EQUAL 1)
            set(${output_variable} "" PARENT_SCOPE)
            return()
        endif()
        list(GET architecture_list 0 target_processor)
    elseif(compiler_architecture)
        set(target_processor "${compiler_architecture}")
    elseif(vs_platform)
        set(target_processor "${vs_platform}")
    elseif(generator_platform)
        set(target_processor "${generator_platform}")
    endif()

    string(TOLOWER "${target_processor}" target_processor)
    if(target_processor MATCHES "^(arm64|aarch64)$")
        set(target_processor arm64)
    elseif(target_processor MATCHES "^(x86_64|amd64|x64)$")
        set(target_processor x86_64)
    endif()
    set(${output_variable} "${target_processor}" PARENT_SCOPE)
endfunction()
